### ISSUE TITLE
Be consistent on usage of IMG / SVG

### ISSUE THREAD

**Issue by Viveur** [flobacher/SVGInjector2#12]
### Noticed some inconsistencies over the use of IMG & SVG in the README documentation that might be confusing for some users:

Wrangling and maintaining a bunch of inline SVG on your pages isn't anyone's idea of good time, so SVGInjector lets you work with simple _**img**_ tag elements (or other tag of your choosing) and does the heavy lifting of swapping in the SVG markup inline for you.

### & then further down:

Add some _**SVG svg**_ tags.

<_**svg**_ class="inject-me" src="image-one.svg">
<_**svg**_ class="inject-me" src="image-two.svg">
Inject 'em.

`var mySVGsToInject = document.querySelectorAll('`_**img**_`.inject-me');`

The **svg** tags have now been replaced with the full SVG markup.

**Comment by flobacher** [comment]
@TheCopartnery I just pushed a new commit to resolve this. Please check.

**Comment by Viveur** [comment]
Cheers. Have added some additional changes that should help clarify behaviour, along with an updated example showing alternative uses.
