### ISSUE TITLE
SVG images with neither data-src nor src trigger an error

### ISSUE THREAD

**Issue by Rush** [flobacher/SVGInjector2#17]
The assumption of this library is that all `svg` elements can be treated with the angular directive. This assumption is clearly wrong. In my app I'm trying to inject only some of the elements and the rest already exists in the DOM.
```
TypeError: Cannot read property 'split' of null
    at n.injectElement (svg-injector.min.js:13)
    at n.inject (svg-injector.min.js:13)
```

Solution would be not to use `svg` for the directive name but rather something like `inject-svg`. Which would be used with:
`<svg inject-svg src="foo.svg">` or `<svg inject-svg data-src="foo.svg">`

**Comment by flobacher** [comment]
should be fixed with the latest release.. please check. thank you!
