### ISSUE TITLE
FYI, version number stuck at v2.0.26

### ISSUE THREAD

**Issue by bridgeport** [flobacher/SVGInjector2#20]
Thanks for this great package. This is just an FYI, but the version number in your latest versions aren't up-to-date. For instance, v2.0.35 is showing:

```
/**
 * SVGInjector v2.0.26 - Fast, caching, dynamic inline SVG DOM injection library
 */
```

within

```
/dist/svg-injector.min.js
/src/svg-injector.js
```

Thanks.

**Comment by flobacher** [comment]
Thx for the hint! Will update this ☺

**Comment by flobacher** [comment]
version comment gets updated as part of the build-pipeline now.
check version 2.0.36
