### ISSUE TITLE
Cannot read property 'replaceChild' of null - Vue app usage

### ISSUE THREAD

**Issue by chasegiunta** [flobacher/SVGInjector2#26]
This is pretty edge case, so I don't expect it to be a high priority, if at all.

The only way I was able to get SVGInjector2 to work in my Vue app was put the trigger in the `updated()` hook.

For whatever reason, couldn't get it working in the usual `mounted()`, `created()`, or other hooks.

Unfortunately, this also means the trigger runs with every subsequent Vue-controlled update causing this error (only _after_ the initial injection). Depending on how many SVGs there are, it can pop up multiple times. Nothing breaks, fortunately, it's just a bit annoying.

```
Uncaught TypeError: Cannot read property 'replaceChild' of null
    at onLoadSVG (svg-injector.js?ff6f:557)
    at eval (svg-injector.js?ff6f:396)
```
`el.parentNode.replaceChild(svg, el);`

Anyway, other than that little caveat, it works great.
Thanks for your work on this @flobacher

**Comment by flobacher** [comment]
nice to see, that it works with vuejs =) I have to admit, that I have no good knowledge of vue-js but I guess one could simply create a `svg-sprite` component, similar to the element directive found in this repo for AngularJS. I do not know why it would not work in the lifecycle hooks, that sound like they are intended to do one time tasks, but if you use it in updated, can't you set a boolean flag, so injection only takes place once? would love to assist you on this, but sadly my time ressource are very limited =/

**Comment by chasegiunta** [comment]
@flobacher No worries. Setting the boolean flag is a great (and obvious) idea I didn't think of. Thanks. You can close if you'd like — I just wanted to notate this use case in case anyone else runs across it or has alternative ideas.

**Comment by rosen91** [comment]
Had the same "issue", except that it does work just fine in the mounted life-cycle hook, everyting worked just fine, but had a couple of thousands error messages in the console, i solved it by editing the replaceChild section with a conditional check:

```
if(el.parentNode) {
    el.parentNode.replaceChild(svg, el);
    delete injections.elements[injections.elements.indexOf(el)];
    injections.count++;
    onElementInjectedCallback(svg);
}
```

Won't submit a pull-request since this is untested in other environments, but could still be useful for someone else getting this issue.

**Comment by nino-vrijman** [comment]
I also had a similar issue today, it only seems to happen when I'm not re-using an SvgInjector instance but creating a new one everytime I'm calling a function like: 
```JavaScript
function doSvgInject() {
  const svgInjector = new SvgInjector(injectorOptions);
  svgInjector.inject(document.querySelectorAll('.some-selector'));
}
```
@rosen91 and @chasegiunta, maybe re-using an SvgInjector instance solves your problems too.

It seems like references to the image elements that should be replaced are stored in a queue here: https://github.com/flobacher/SVGInjector2/blob/a1c5b79c45a1ddb572858b12dd7dcfdae515bb35/src/svg-injector.js#L651 After I did some debugging I noticed that image elements that are referenced on the line I mentioned somehow aren't removed from the queue (but they get added multiple times) after they have been replaced by the inline svg variant.

EDIT:
Can be reproduced here: https://svg-injector-2-issue-reproduction-duiunobcuq.now.sh/, source: https://github.com/nino-vrijman/svg-injector-2-replace-child-issue. 

1. Click '1) Go to this page'
2. Click '2) Go back to index (error will occur)'
3. Check the console to see the error.

You can see that image elements aren't removed from the queue if you go to the debugger -> 'svg-injector.js', set a breakpoint at line 392, switch pages again and check the contents of 'requestQueue'.
