### ISSUE TITLE
Chrome scrollbar disappearing

### ISSUE THREAD

**Issue by elemis** [flobacher/SVGInjector2#30]
Having a scrollbar issue on websites with SVGInjector on Chrome (Mac & Windows). Occasionally the scrollbar disappears as soon as a page loads, and reappears scrolling down. Happens on pages where SVGInjector is being used. Removing SVGInjector plugin resolves the issue. The issue appears on all websites we know that has SVGInjector (Both versions 1 & 2).

Any idea what might be causing this?

URL for testing: https://sandbox.elemisthemes.com/test/

Screencasts for demonstration:
https://user-images.githubusercontent.com/608547/146539023-0322a9b4-1b81-44f2-a106-0abe06b44755.mov
https://user-images.githubusercontent.com/608547/146539057-b570c99b-0d7a-4451-9315-d9416f1ff964.mov

**Comment by flobacher** [comment]
I think thats neither a bug of svg-injector nor any other js, html or css on the page.. its a setting that controls if the browser will always render scrollbars, or only on demand.. 
on macOS the os  controls this behaviour. Attched you find a screenshot of the preferences menu:

<img width="666" alt="image" src="https://user-images.githubusercontent.com/9580206/146840602-fcda985e-e73d-419b-8dc9-f5b18a530f92.png">

**Comment by pixibuex** [comment]
@flobacher Already have this setting as Always. Also as mentioned before the issue occurs on Windows Chrome as well, here's a screencast from Windows: 

https://user-images.githubusercontent.com/8955300/146879606-b4bd512f-083d-4c9b-9a37-1ce8007726d8.mp4

**Comment by elemis** [comment]
@flobacher Already have this setting as Always. Also as mentioned before the issue occurs on Windows Chrome as well, here's a screencast from Windows:

https://user-images.githubusercontent.com/608547/146879791-aac8d9b2-0a60-4890-a8a4-ecb7bea11816.mp4

**Comment by flobacher** [comment]
@elemis I justed tried on mac os catalina in latest stable chrome (96) and safari (15.2) with the "show always" scrollbar setting and I always see scrollbars when navigating betwenn project2 and pricing [sandbox.elemisthemes.com/test](https://sandbox.elemisthemes.com/test).. cannot think of any possible way svg-injector could be the reason for this behavior... might it be some other js on the page or even some chrome extension?
